version: '3'

services:
  app:
    build:
      context: ./
    container_name: facevalidation_app
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - .env
    restart: always
    networks:
      default:
    volumes:
      - images:/home/python/images
    ports:
      - "7998:80"

  cv:
    build:
      context: ./cv
      dockerfile: ./cv/cpu.Dockerfile
      # dockerfile: ./cv/gpu.Dockerfile
    depends_on:
      - rabbitmq
    env_file:
      - .env
    restart: always
    volumes:
      - images:/home/python/images
    networks:
      default:

  postgres:
    image: postgres:latest
    container_name: facevalidation_db
    restart: always
    env_file:
      - .env
    networks:
      default:

  rabbitmq:
    image: rabbitmq:management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persist data
    networks:
      default:

volumes:
  rabbitmq_data:
  images:

networks:
  default:
