"""add profile

Revision ID: 155d31e6287b
Revises: b8c234fa02ee
Create Date: 2025-02-25 19:40:03.804711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '155d31e6287b'
down_revision = 'b8c234fa02ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_items', sa.Column('is_profile', sa.Boolean(), nullable=True))
    op.add_column('task_items', sa.Column('is_halfprofile', sa.Boolean(), nullable=True))
    op.drop_column('task_items', 'is_rotation_huge')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_items', sa.Column('is_rotation_huge', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('task_items', 'is_halfprofile')
    op.drop_column('task_items', 'is_profile')
    # ### end Alembic commands ###
