"""multiple files

Revision ID: 6921696103a6
Revises: 9af8f1f08c31
Create Date: 2025-02-20 11:00:43.450029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6921696103a6'
down_revision = '9af8f1f08c31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_items', sa.Column('image_index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_items', 'image_index')
    # ### end Alembic commands ###
