"""add nullable

Revision ID: 725576d09cd1
Revises: a22b1c472911
Create Date: 2025-02-20 13:12:28.489087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '725576d09cd1'
down_revision = 'a22b1c472911'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_items', sa.Column('error', sa.String(), nullable=True))
    op.alter_column('task_items', 'left_eye_close',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('task_items', 'right_eye_close',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('task_items', 'is_eyes_closed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('task_items', 'face_left',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('task_items', 'face_top',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('task_items', 'face_bottom',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('task_items', 'face_right',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('task_items', 'is_face_small',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('task_items', 'image_width',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('task_items', 'image_height',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('task_items', 'with_glasses',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('task_items', 'image_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_items', 'image_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('task_items', 'with_glasses',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('task_items', 'image_height',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('task_items', 'image_width',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('task_items', 'is_face_small',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('task_items', 'face_right',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('task_items', 'face_bottom',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('task_items', 'face_top',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('task_items', 'face_left',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('task_items', 'is_eyes_closed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('task_items', 'right_eye_close',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('task_items', 'left_eye_close',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('task_items', 'error')
    # ### end Alembic commands ###
