"""items vote

Revision ID: a22b1c472911
Revises: 6921696103a6
Create Date: 2025-02-20 11:15:59.836442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a22b1c472911'
down_revision = '6921696103a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_items', sa.Column('is_good', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_items', 'is_good')
    # ### end Alembic commands ###
