"""add rotation

Revision ID: b8c234fa02ee
Revises: 725576d09cd1
Create Date: 2025-02-24 02:20:30.274892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8c234fa02ee'
down_revision = '725576d09cd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_items', sa.Column('rotation', sa.Float(), nullable=True))
    op.add_column('task_items', sa.Column('is_rotation_huge', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_items', 'is_rotation_huge')
    op.drop_column('task_items', 'rotation')
    # ### end Alembic commands ###
